### ISSUE TITLE
Move basic Pandas exercises from slides to exercise 3

### ISSUE THREAD

**Issue by margrietpalm** [lacdr-tox/basic-programming-in-drug-discovery#1]
Move the short Pandas exercises that are in the slides to exercise 3.

**Comment by BrandonFlux** [comment]
If you have done this, i will continue with creating the exercise, so that we dont duplicate stuff

**Comment by margrietpalm** [comment]
@BrandonFlux ik doe dit zsm

**Comment by margrietpalm** [comment]
Ik heb de content uit de slides in het notebook gezet (maar nog niet uit de slides gehaald) en voorbeelden gemaakt met de *Cellscreens* data (572d31d322cf48d39bfc300b4143a617117fd3c1). De antwoorden staan nu nog in de opgaven, en dat moet natuurlijk gesplitst worden.
