### ISSUE TITLE
Set up exercise for changing font size, line color, etc.

### ISSUE THREAD

**Issue by margrietpalm** [lacdr-tox/basic-programming-in-drug-discovery#12]
* Use `plot` arguments: `fmt`, `color`, `linestyle`, `linewidth`, `marker`, `markersize`, 
* named colors
* Use `errorbars` arguments: `ecolor`, `elinewidth`, `capsize`, `capthick`, `barsabove`, 

Resources
* https://matplotlib.org/api/_as_gen/matplotlib.pyplot.plot.html
* https://matplotlib.org/api/_as_gen/matplotlib.pyplot.errorbar.html

**Comment by margrietpalm** [comment]
@BrandonFlux In hoeverre behandel je in exercise 2:
* `linestyle` en `color`
* `legend` positioning

**Comment by BrandonFlux** [comment]
Legend positioning niet, alleen dat deze er is.
Ik denk dat het handig is als ik linestyle en color behandel

**Comment by margrietpalm** [comment]
Misschien kun je het gebruik van `loc` daar benoemen? Dan kan ik bij de subplots nog behandelen hoe je de legend buiten een plot krijgt.

**Comment by BrandonFlux** [comment]
Noted, Zal ik doen

**Comment by BrandonFlux** [comment]
@margrietpalm Bedoel je loc als argument? of mis ik een functie

**Comment by margrietpalm** [comment]
Oeps, sorry voor de late reactie. Idd het `loc` argument van `legend`.
