### ISSUE TITLE
Plots exporteren

### ISSUE THREAD

**Issue by margrietpalm** [lacdr-tox/basic-programming-in-drug-discovery#14]
@BrandonFlux Doen we het exporteren van plots (`plt.savefig`) in opgave 2 of 4?

**Comment by BrandonFlux** [comment]
Ik kan dit wel in opgave 2 doen lijkt me, in principe hoort dit bij de 'basis' dingen denk ik?

**Comment by margrietpalm** [comment]
Mij ook. Kun je dan laten zien hoe je:
- bitmaps maakt (.png)
- vector graphics (.svg)

**Comment by BrandonFlux** [comment]
Noted, zal het erin zitten
