### ISSUE TITLE
Autoscaling still does not work

### ISSUE THREAD

**Issue by BrandonFlux** [lacdr-tox/basic-programming-in-drug-discovery#5]
Setting a scale still does not work. Attached are pictures on what is happening.

Setting the ylim after plotting completely breaks the y-axis, forcing everything down. I have no idea what is causing this unfortunately, and need some help with this before i can complete this and the next exercise

Normal Situation
![scaling-normal](https://user-images.githubusercontent.com/11915535/46671830-1c1e7c80-cbd6-11e8-9d3a-c8c9c81ccb76.PNG)
 
Using ylim method 1
![scaling-1](https://user-images.githubusercontent.com/11915535/46671828-1b85e600-cbd6-11e8-8537-51843b4fb2cc.PNG)

Using ylim method 2
![scaling-2](https://user-images.githubusercontent.com/11915535/46671829-1b85e600-cbd6-11e8-9eb7-4dccbbccf9ad.PNG)

**Comment by margrietpalm** [comment]
Dit is geen probleem met de scaling, maar met de yticks. Echter, in dit geval is het probleem dat je een lijst met strings probeert te plotten, en dan gebruikt matplotlib blijkbaar de indices als positie en zet de bijbehorende waardes op de assen. Zie ook voorbeeld in `python/sandbox/fig-plot_issue.ipynb` (aeb3997dcd9d2c5d130a985a85af0d9b29004202).
